import { env } from "cloudflare:workers";
const date=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok"}).format(new Date()); const now=()=>new Date().toISOString();
const rules:Record<string,[string,number[]]>={"image/jpeg":["jpg",[255,216,255]],"image/png":["png",[137,80,78,71]],"image/webp":["webp",[82,73,70,70]]};
async function me(r:Request){const s=r.headers.get("cookie")?.match(/(?:^|;\s*)fivek_session=([^;]+)/);return s?env.DB.prepare("SELECT m.* FROM sessions s JOIN members m ON m.id=s.member_id WHERE s.token=? AND s.expires_at>? AND m.active=1").bind(s[1],now()).first<any>():null}
async function image(file:File){const rule=rules[file.type];if(!rule||file.size>8*1024*1024)throw Error("ใช้ไฟล์ JPG, PNG หรือ WebP ขนาดไม่เกิน 8 MB");const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());if(!rule[1].every((n,i)=>bytes[i]===n)||(file.type==="image/webp"&&String.fromCharCode(...bytes.slice(8,12))!=="WEBP"))throw Error("ชนิดไฟล์รูปภาพไม่ถูกต้อง");return rule[0]}
export async function POST(r:Request){let key="";try{const member=await me(r);if(!member)return Response.json({error:"กรุณาเข้าสู่ระบบ"},{status:401});const form=await r.formData(),file=form.get("image"),type=String(form.get("type"));if(!(file instanceof File)||!file.size)throw Error("กรุณาเลือกรูปหลักฐาน");const ext=await image(file),today=date();
if(type==="airdrop"){const round=String(form.get("round"));if(round!=="20:00"&&round!=="23:00")throw Error("เลือกรอบไม่ถูกต้อง");const old=await env.DB.prepare("SELECT id,status,image_key FROM airdrop_submissions WHERE member_id=? AND activity_date=? AND round_time=?").bind(member.id,today,round).first<any>();if(old?.status==="approved")throw Error("หลักฐานที่ผ่านแล้วไม่สามารถแก้ไขได้");key=`airdrop/${member.id}/${Date.now()}.${ext}`;await env.BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type,contentDisposition:"inline"}});if(old){const updated=await env.DB.prepare("UPDATE airdrop_submissions SET image_key=?,status='pending',approved_by=NULL,created_at=? WHERE id=? AND status<>'approved'").bind(key,now(),old.id).run();if(!updated.meta.changes)throw Error("หลักฐานรายการนี้เพิ่งผ่านการตรวจ จึงแก้ไขไม่ได้");}else await env.DB.prepare("INSERT INTO airdrop_submissions (member_id,activity_date,round_time,image_key,status,created_at) VALUES (?,?,?,?, 'pending',?)").bind(member.id,today,round,key,now()).run();if(old?.image_key)await env.BUCKET.delete(old.image_key)}
else if(type==="party"){const ids=JSON.parse(String(form.get("memberIds")||"[]")).map(Number);if(ids.length<1||ids.length>5||new Set(ids).size!==ids.length)throw Error("เลือกสมาชิกปาร์ตี้ได้ 1 ถึง 5 คน");const check=await env.DB.prepare(`SELECT id FROM members WHERE active=1 AND id IN (${ids.map(()=>"?").join(",")})`).bind(...ids).all();if(check.results.length!==ids.length)throw Error("พบสมาชิกที่เลือกไม่ถูกต้อง");key=`party/${member.id}/${Date.now()}.${ext}`;await env.BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type,contentDisposition:"inline"}});const party=await env.DB.prepare("INSERT INTO parties (name,active) VALUES (?,0)").bind(`กิจกรรม ${today} ${Date.now()}`).run(),activity=await env.DB.prepare("INSERT INTO party_activities (party_id,activity_date,image_key,status,submitted_by_member_id,created_at) VALUES (?,?,?,'pending',?,?)").bind(party.meta.last_row_id,today,key,member.id,now()).run();await env.DB.batch(ids.map((id:number)=>env.DB.prepare("INSERT INTO party_activity_members (party_activity_id,member_id) VALUES (?,?)").bind(activity.meta.last_row_id,id)))}else throw Error("ประเภทไม่ถูกต้อง");return Response.json({ok:true})}catch(e){if(key)await env.BUCKET.delete(key);return Response.json({error:e instanceof Error?e.message:"อัปโหลดไม่สำเร็จ"},{status:400})}}

