import { env } from "cloudflare:workers";

const now=()=>new Date().toISOString();
const json=(data:unknown,status=200)=>Response.json(data,{status});
async function currentMember(request:Request){const c=request.headers.get("cookie")?.match(/(?:^|;\s*)fivek_session=([^;]+)/);if(!c)return null;return env.DB.prepare("SELECT m.* FROM sessions s JOIN members m ON m.id=s.member_id WHERE s.token=? AND s.expires_at>? AND m.active=1").bind(c[1],now()).first<any>();}
async function requireMember(request:Request){const member=await currentMember(request);if(!member)throw Error("กรุณาเข้าสู่ระบบก่อนใช้งาน");return member;}
async function activeParty(memberId:number){return env.DB.prepare("SELECT p.id,p.name,p.status,p.owner_member_id FROM parties p JOIN party_members pm ON pm.party_id=p.id WHERE pm.member_id=? AND p.status IN ('open','locked') LIMIT 1").bind(memberId).first<any>();}

export async function POST(request:Request){try{const me=await requireMember(request),body=await request.json<any>();
if(body.action==="party_create"){const name=String(body.name||"").trim();if(name.length<2||name.length>40)throw Error("ชื่อปาร์ตี้ต้องมี 2–40 ตัวอักษร");if(await activeParty(me.id))throw Error("คุณอยู่ในปาร์ตี้ที่กำลังใช้งานอยู่แล้ว");const party=await env.DB.prepare("INSERT INTO parties (name,owner_member_id,status,active) VALUES (?,?,?,1)").bind(name,me.id,"open").run();await env.DB.prepare("INSERT INTO party_members (party_id,member_id,joined_at) VALUES (?,?,?)").bind(party.meta.last_row_id,me.id,now()).run();return json({ok:true});}
if(body.action==="party_invite"){const partyId=Number(body.partyId),memberId=Number(body.memberId),party=await env.DB.prepare("SELECT id,owner_member_id,status FROM parties WHERE id=? AND active=1").bind(partyId).first<any>();if(!party||party.owner_member_id!==me.id||party.status!=="open")throw Error("เฉพาะหัวหน้าปาร์ตี้ที่เปิดรับสมาชิกเท่านั้น");const count=await env.DB.prepare("SELECT COUNT(*) AS total FROM party_members WHERE party_id=?").bind(partyId).first<any>();if(Number(count?.total||0)>=5)throw Error("ปาร์ตี้เต็มแล้ว");const target=await env.DB.prepare("SELECT id FROM members WHERE id=? AND active=1").bind(memberId).first();if(!target||memberId===me.id)throw Error("ไม่พบสมาชิกที่เลือก");if(await activeParty(memberId))throw Error("สมาชิกคนนี้อยู่ในปาร์ตี้อื่นแล้ว");const existing=await env.DB.prepare("SELECT id,status FROM party_invites WHERE party_id=? AND invitee_member_id=?").bind(partyId,memberId).first<any>();if(existing)await env.DB.prepare("UPDATE party_invites SET inviter_member_id=?,status='pending',created_at=?,responded_at=NULL WHERE id=?").bind(me.id,now(),existing.id).run();else await env.DB.prepare("INSERT INTO party_invites (party_id,inviter_member_id,invitee_member_id,status,created_at) VALUES (?,?,?,'pending',?)").bind(partyId,me.id,memberId,now()).run();return json({ok:true});}
if(body.action==="party_respond"){const inviteId=Number(body.inviteId),invite=await env.DB.prepare("SELECT i.id,i.party_id,p.status FROM party_invites i JOIN parties p ON p.id=i.party_id WHERE i.id=? AND i.invitee_member_id=? AND i.status='pending'").bind(inviteId,me.id).first<any>();if(!invite)throw Error("ไม่พบคำเชิญหรือคำเชิญหมดอายุแล้ว");if(body.accept){if(await activeParty(me.id))throw Error("คุณอยู่ในปาร์ตี้อื่นแล้ว");const count=await env.DB.prepare("SELECT COUNT(*) AS total FROM party_members WHERE party_id=?").bind(invite.party_id).first<any>();if(invite.status!=="open"||Number(count?.total||0)>=5)throw Error("ปาร์ตี้นี้เต็มหรือปิดรับสมาชิกแล้ว");await env.DB.batch([env.DB.prepare("UPDATE party_invites SET status='accepted',responded_at=? WHERE id=?").bind(now(),inviteId),env.DB.prepare("INSERT OR IGNORE INTO party_members (party_id,member_id,joined_at) VALUES (?,?,?)").bind(invite.party_id,me.id,now())]);}else await env.DB.prepare("UPDATE party_invites SET status='rejected',responded_at=? WHERE id=?").bind(now(),inviteId).run();return json({ok:true});}
if(body.action==="party_join"){const partyId=Number(body.partyId);if(await activeParty(me.id))throw Error("คุณอยู่ในปาร์ตี้ที่กำลังใช้งานอยู่แล้ว");const party=await env.DB.prepare("SELECT id FROM parties WHERE id=? AND status='open' AND active=1").bind(partyId).first<any>();if(!party)throw Error("ปาร์ตี้นี้ปิดรับสมาชิกแล้ว");const count=await env.DB.prepare("SELECT COUNT(*) AS total FROM party_members WHERE party_id=?").bind(partyId).first<any>();if(Number(count?.total||0)>=5)throw Error("ปาร์ตี้เต็มแล้ว");await env.DB.prepare("INSERT OR IGNORE INTO party_members (party_id,member_id,joined_at) VALUES (?,?,?)").bind(partyId,me.id,now()).run();return json({ok:true});}
if(body.action==="party_lock"){const party=await env.DB.prepare("SELECT id,owner_member_id FROM parties WHERE id=? AND active=1").bind(Number(body.partyId)).first<any>();if(!party||party.owner_member_id!==me.id)throw Error("เฉพาะหัวหน้าปาร์ตี้เท่านั้น");const status=body.locked?"locked":"open";await env.DB.prepare("UPDATE parties SET status=? WHERE id=?").bind(status,party.id).run();return json({ok:true});}
if(body.action==="party_leave"){const party=await env.DB.prepare("SELECT p.id,p.owner_member_id FROM parties p JOIN party_members pm ON pm.party_id=p.id WHERE pm.member_id=? AND p.status IN ('open','locked') LIMIT 1").bind(me.id).first<any>();if(!party)throw Error("คุณไม่ได้อยู่ในปาร์ตี้");const next=party.owner_member_id===me.id?await env.DB.prepare("SELECT member_id FROM party_members WHERE party_id=? AND member_id<>? ORDER BY id LIMIT 1").bind(party.id,me.id).first<any>():null;const statements=[env.DB.prepare("DELETE FROM party_members WHERE party_id=? AND member_id=?").bind(party.id,me.id)];if(next)statements.push(env.DB.prepare("UPDATE parties SET owner_member_id=? WHERE id=?").bind(next.member_id,party.id));else if(party.owner_member_id===me.id)statements.push(env.DB.prepare("UPDATE parties SET status='completed',active=0 WHERE id=?").bind(party.id));await env.DB.batch(statements);return json({ok:true});}
if(body.action==="party_remove_member"){const party=await activeParty(me.id);if(!party||party.owner_member_id!==me.id)throw Error("เฉพาะหัวหน้าปาร์ตี้เท่านั้น");const memberId=Number(body.memberId);if(memberId===me.id)throw Error("หัวหน้าต้องใช้ปุ่มออกจากปาร์ตี้");await env.DB.prepare("DELETE FROM party_members WHERE party_id=? AND member_id=?").bind(party.id,memberId).run();return json({ok:true});}
throw Error("คำสั่งปาร์ตี้ไม่ถูกต้อง");
}catch(error){return json({error:error instanceof Error?error.message:"บันทึกปาร์ตี้ไม่สำเร็จ"},400)}}
