"use client";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { Camera, Check, Crosshair, ShieldCheck, Star, Trophy, Upload, Users } from "lucide-react";

type Data={me:{id:number;name:string;role:string;score:number};date:string;members:any[];airdrops:any[];parties:any[];favorites:number[];leaderboard:any[];pending:any[]};
const labels:Record<string,string>={pending:"รอตรวจ",approved:"ผ่านแล้ว",rejected:"ไม่ผ่าน"};
function Status({value}:{value:string}){return <span className={`rounded-full px-3 py-1 text-xs font-bold ${value==="approved"?"bg-emerald-500/15 text-emerald-300":value==="rejected"?"bg-red-500/15 text-red-300":"bg-amber-400/15 text-amber-200"}`}>{labels[value]||value}</span>}
function Picker({onChange}:{onChange:(f:File|null)=>void}){const [name,setName]=useState("เลือกรูปหลักฐาน");return <label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed border-white/20 bg-black/20 px-4 py-5 text-sm text-slate-300 hover:border-red-400"><Camera className="h-5 w-5 text-red-400"/>{name}<input className="sr-only" type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0]||null;setName(f?.name||"เลือกรูปหลักฐาน");onChange(f)}}/></label>}
export default function Home(){
 const [data,setData]=useState<Data|null>(null),[view,setView]=useState("airdrop"),[round,setRound]=useState<"20:00"|"22:00">("20:00"),[image,setImage]=useState<File|null>(null),[crew,setCrew]=useState<number[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[name,setName]=useState(""),[authNeeded,setAuthNeeded]=useState(false);
 const load=async()=>{const r=await fetch("/api/dashboard",{cache:"no-store"}),x:any=await r.json();if(r.status===401)setAuthNeeded(true); else if(x.error)setNotice(x.error);else setData(x)};useEffect(()=>{load()},[]);
 const mine=useMemo(()=>new Map(data?.airdrops.map((x:any)=>[x.round_time,x])||[]),[data]);
 const call=async(body:any)=>{setBusy(true);const r=await fetch("/api/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),x:any=await r.json();setBusy(false);setNotice(x.error||"บันทึกแล้ว");if(!x.error)load()};
 const send=async(type:"airdrop"|"party",e:FormEvent)=>{e.preventDefault();if(!image)return setNotice("กรุณาเลือกรูปหลักฐาน");setBusy(true);const f=new FormData();f.append("type",type);f.append("image",image);if(type==="airdrop")f.append("round",round);else f.append("memberIds",JSON.stringify(crew));const r=await fetch("/api/upload",{method:"POST",body:f}),x:any=await r.json();setBusy(false);setNotice(x.error||"ส่งเข้าคิวตรวจแล้ว");if(!x.error){setImage(null);setCrew([]);load()}};
 if(!data&&authNeeded)return <main className="grid min-h-screen place-items-center bg-[#07080b] p-5 text-white"><section className="command-panel w-full max-w-md p-7 text-center"><img src="/5k-logo.png" alt="5K Fivethousand" className="mx-auto h-28 w-full object-contain"/><h1 className="mt-5 text-2xl font-black">เข้าสู่ระบบแก๊ง</h1><p className="mt-3 text-sm text-slate-400">ใช้บัญชี ChatGPT ของคุณเข้าสู่ระบบครั้งแรก แอดมินต้องเพิ่มอีเมลของคุณไว้ก่อน</p><a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="red-action mt-6 w-full">เข้าสู่ระบบด้วย ChatGPT</a></section></main>;
 if(!data)return <main className="grid min-h-screen place-items-center bg-[#07080b] text-white">กำลังเปิดศูนย์บัญชาการ…</main>;
 const members=[...data.members].sort((a,b)=>Number(data.favorites.includes(b.id))-Number(data.favorites.includes(a.id))||a.display_name.localeCompare(b.display_name));
 const nav:[string,string,any][]=[["airdrop","แอร์ดรอป",Crosshair],["party","ปาร์ตี้",Users],["score","คะแนน",Trophy],["admin","จัดการแก๊ง",ShieldCheck]];
 return <main className="min-h-screen bg-[#07080b] text-white"><div className="command-grid fixed inset-0 pointer-events-none opacity-30"/><div className="relative mx-auto flex max-w-7xl gap-6 p-4 lg:p-7"><aside className="hidden w-60 shrink-0 lg:block"><img src="/5k-logo.png" alt="5K Fivethousand" className="h-28 w-full object-contain"/><nav className="mt-7 space-y-2">{nav.map(([id,label,Icon]:any)=><button key={id} onClick={()=>setView(id)} className={`flex w-full items-center gap-3 rounded-lg px-4 py-3 text-left font-bold ${view===id?"bg-red-600":"text-slate-400 hover:bg-white/5"}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav></aside><section className="min-w-0 flex-1"><header className="mb-6 flex items-center justify-between border-b border-white/10 pb-4"><div><img src="/5k-logo.png" alt="5K" className="h-12 w-24 object-contain lg:hidden"/><p className="hidden text-sm text-slate-400 lg:block">{data.date} · ประเทศไทย</p></div><div className="text-right"><b>{data.me.name}</b><p className="text-xs text-red-400">{data.me.role==="admin"?"ADMINISTRATOR":"MEMBER"}</p></div></header><div className="command-hero mb-5 rounded-xl border border-red-500/25 p-5"><p className="label">FIVETHOUSAND COMMAND CENTER</p><div className="mt-2 flex items-end justify-between gap-4"><div><h1 className="text-2xl font-black sm:text-3xl">แต้มของคุณ <span className="text-red-500">{data.me.score} PTS</span></h1><p className="mt-2 text-sm text-slate-400">แอร์ดรอป 2 รอบ: +3 ต่อรอบ · ปาร์ตี้ 5 คน: +1 ต่อคนเมื่อผ่าน</p></div><button onClick={load} className="rounded-lg border border-white/15 px-3 py-2 text-sm">รีเฟรช</button></div></div><div className="mb-5 flex gap-2 overflow-x-auto lg:hidden">{nav.map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm ${view===id?"bg-red-600":"bg-white/10"}`}>{label}</button>)}</div>{notice&&<div className="mb-5 flex items-center justify-between rounded-lg border border-red-400/30 bg-red-950/30 px-4 py-3 text-sm"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
 {view==="airdrop"&&<div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><form onSubmit={e=>send("airdrop",e)} className="command-panel p-5"><p className="label">AIRDROP CHECK-IN</p><h2 className="mt-2 text-xl font-black">ส่งหลักฐานแอร์ดรอป</h2><div className="mt-5 grid grid-cols-2 gap-3">{(["20:00","22:00"] as const).map(t=>{const x=mine.get(t);return <button type="button" key={t} onClick={()=>setRound(t)} className={`rounded-lg border p-4 text-left ${round===t?"border-red-500 bg-red-950/30":"border-white/10"}`}><b className="text-2xl">{t}</b><p className="mt-3">{x?<Status value={x.status}/>:<span className="text-sm text-slate-400">ยังไม่ส่ง</span>}</p></button>})}</div><div className="mt-5"><Picker onChange={setImage}/></div><button disabled={busy||!!mine.get(round)} className="red-action mt-4 w-full disabled:opacity-40"><Upload className="h-5 w-5"/>{mine.get(round)?"รอบนี้ส่งแล้ว":"ส่งรอบ "+round}</button></form><section className="command-panel p-5"><p className="label">ประวัติแอร์ดรอป</p><div className="mt-4 space-y-2">{data.airdrops.length?data.airdrops.map((x:any)=><div key={x.id} className="flex items-center justify-between rounded-lg bg-white/5 p-3"><div><b>รอบ {x.round_time}</b><p className="text-xs text-slate-500">{new Date(x.created_at).toLocaleString("th-TH")}</p></div><Status value={x.status}/></div>):<p className="text-slate-400">ยังไม่มีประวัติ</p>}</div></section></div>}
 {view==="party"&&<div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><form onSubmit={e=>send("party",e)} className="command-panel p-5"><div className="flex justify-between"><div><p className="label">AD-HOC PARTY</p><h2 className="mt-2 text-xl font-black">รวมตี้ใหม่สำหรับกิจกรรมนี้</h2></div><b className="text-red-400">{crew.length}/5 คน</b></div><p className="mt-2 text-sm text-slate-400">เลือกได้ 1–5 คน ตี้นี้ใช้ครั้งเดียว แล้วรวมทีมใหม่ในกิจกรรมถัดไปได้ทันที</p><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{members.map((m:any)=>{const chosen=crew.includes(m.id),star=data.favorites.includes(m.id);return <div key={m.id} className={`relative rounded-lg border ${chosen?"border-red-500 bg-red-950/30":"border-white/10"}`}><button type="button" onClick={()=>setCrew(c=>chosen?c.filter(i=>i!==m.id):c.length<5?[...c,m.id]:c)} className="w-full p-3 text-left"><b className="block truncate">{m.display_name}</b><span className="text-xs text-slate-500">{m.role}</span></button><button type="button" aria-label="ติดดาวสมาชิก" onClick={()=>call({action:"favorite",memberId:m.id,enabled:!star})} className={`absolute right-2 top-2 ${star?"text-amber-300":"text-slate-600"}`}><Star className={`h-4 w-4 ${star?"fill-current":""}`}/></button></div>})}</div><div className="mt-5"><Picker onChange={setImage}/></div><button disabled={busy||crew.length<1} className="red-action mt-4 w-full disabled:opacity-40"><Camera className="h-5 w-5"/>สร้างตี้และส่งรูป</button></form><section className="command-panel p-5"><p className="label">ประวัติปาร์ตี้</p><div className="mt-4 space-y-2">{data.parties.length?data.parties.map((p:any)=><div key={p.id} className="rounded-lg bg-white/5 p-3"><div className="flex justify-between gap-2"><b>กิจกรรม #{p.id}</b><Status value={p.status}/></div><p className="mt-2 text-sm text-slate-400">{p.members}</p></div>):<p className="text-slate-400">ยังไม่มีรายการปาร์ตี้</p>}</div></section></div>}
 {view==="score"&&<section className="command-panel overflow-hidden"><div className="border-b border-white/10 p-5"><p className="label">SQUAD RANKING</p><h2 className="mt-2 text-xl font-black">ตารางคะแนนจริง</h2></div>{data.leaderboard.map((m:any,i:number)=><div className="flex items-center gap-4 border-b border-white/10 p-4 last:border-0" key={m.id}><b className="w-8 text-red-400">{i+1}</b><span className="flex-1 font-bold">{m.display_name}</span><b className="font-mono text-red-400">{m.score} PTS</b></div>)}</section>}
 {view==="admin"&&(data.me.role!=="admin"?<section className="command-panel p-6">หน้านี้สำหรับแอดมินเท่านั้น</section>:<div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="command-panel p-5"><p className="label">VERIFY QUEUE</p><h2 className="mt-2 text-xl font-black">รายการรอตรวจ</h2><div className="mt-4 space-y-3">{data.pending.length?data.pending.map((x:any)=><div key={x.type+x.id} className="rounded-lg border border-white/10 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><b>{x.type==="party"?"ปาร์ตี้":"แอร์ดรอป"} #{x.id}</b><p className="text-sm text-slate-400">{x.detail}</p></div><div className="flex gap-2"><a className="rounded bg-white/10 px-3 py-2 text-sm" href={`/api/image/${x.image_key}`} target="_blank">ดูรูป</a><button onClick={()=>call({action:"approve",type:x.type,id:x.id})} className="rounded bg-emerald-600 px-3 py-2 text-sm"><Check className="h-4 w-4"/></button><button onClick={()=>call({action:"reject",type:x.type,id:x.id})} className="rounded bg-red-700 px-3 py-2 text-sm">ไม่ผ่าน</button></div></div></div>):<p className="text-slate-400">ไม่มีรายการรอตรวจ</p>}</div></section><section className="command-panel p-5"><p className="label">SQUAD MANAGEMENT</p><h2 className="mt-2 text-xl font-black">เพิ่มสมาชิก</h2><form onSubmit={e=>{e.preventDefault();const email=window.prompt("อีเมล ChatGPT ของสมาชิก");if(email){call({action:"member",name,email});setName("")}}} className="mt-4 flex gap-2"><input value={name} onChange={(e:ChangeEvent<HTMLInputElement>)=>setName(e.target.value)} placeholder="ชื่อสมาชิก" className="min-w-0 flex-1 rounded-lg border border-white/15 bg-black/30 px-3 py-2"/><button className="rounded-lg bg-red-600 px-3 font-bold">เพิ่ม</button></form><p className="mt-3 text-xs text-slate-400">กรอกชื่อ แล้วระบบจะถามอีเมล ChatGPT เพื่อเชื่อมบัญชีเมื่อสมาชิก Login ครั้งแรก</p><p className="mt-5 text-sm text-slate-400">สมาชิกทั้งหมด {data.members.length} คน</p></section></div>)}
 </section></div></main>
}
