"use client";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { Camera, Check, Crosshair, LogOut, ShieldCheck, Star, Trophy, Upload, Users } from "lucide-react";

type Data={me:{id:number;name:string;role:string;score:number};date:string;members:any[];managedMembers:any[];airdrops:any[];parties:any[];favorites:number[];leaderboard:any[];pending:any[]};
const labels:Record<string,string>={pending:"รอตรวจ",approved:"ผ่านแล้ว",rejected:"ไม่ผ่าน"};
function Status({value}:{value:string}){return <span className={`rounded-full px-3 py-1 text-xs font-bold ${value==="approved"?"bg-emerald-500/15 text-emerald-300":value==="rejected"?"bg-red-500/15 text-red-300":"bg-amber-400/15 text-amber-200"}`}>{labels[value]||value}</span>}
function Picker({onChange}:{onChange:(file:File|null)=>void}){const [filename,setFilename]=useState("เลือกรูปหลักฐาน");return <label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed border-white/20 bg-black/20 px-4 py-5 text-sm text-slate-300 hover:border-red-400"><Camera className="h-5 w-5 text-red-400"/>{filename}<input className="sr-only" type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0]||null;setFilename(file?.name||"เลือกรูปหลักฐาน");onChange(file)}}/></label>}

export default function Home(){
 const [data,setData]=useState<Data|null>(null),[view,setView]=useState("airdrop"),[round,setRound]=useState<"20:00"|"22:00">("20:00"),[image,setImage]=useState<File|null>(null),[crew,setCrew]=useState<number[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[name,setName]=useState(""),[authNeeded,setAuthNeeded]=useState(false),[loginName,setLoginName]=useState("");
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/dashboard",{cache:"no-store"}),x:any=await r.json();if(r.status===401){setData(null);setAuthNeeded(true)}else if(x.error)setNotice(x.error);else{setData(x);setAuthNeeded(false)}}catch{setNotice("เชื่อมต่อระบบไม่สำเร็จ ลองรีเฟรชอีกครั้ง")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{const id="loading-indicator";let el=document.getElementById(id);if(loading||busy){if(!el){el=document.createElement("div");el.id=id;el.setAttribute("role","status");Object.assign(el.style,{position:"fixed",right:"20px",bottom:"20px",zIndex:"100",padding:"12px 16px",borderRadius:"10px",background:"#18090c",border:"1px solid rgba(248,113,113,.5)",color:"#fee2e2",fontSize:"14px",boxShadow:"0 8px 24px rgba(0,0,0,.4)"});document.body.appendChild(el)}el.textContent=loading?"กำลังโหลดข้อมูล…":"กำลังบันทึกข้อมูล…"}else if(el)el.remove();return()=>{document.getElementById(id)?.remove()}},[loading,busy]);
 const mine=useMemo(()=>new Map(data?.airdrops.filter((x:any)=>x.activity_date===data.date).map((x:any)=>[x.round_time,x])||[]),[data]);
 const call=async(body:any)=>{setBusy(true);try{const r=await fetch("/api/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),x:any=await r.json();setNotice(x.error||"บันทึกแล้ว");if(!x.error)await load()}catch{setNotice("บันทึกไม่สำเร็จ ลองใหม่อีกครั้ง")}finally{setBusy(false)}};
 const send=async(type:"airdrop"|"party",event:FormEvent)=>{event.preventDefault();if(!image)return setNotice("กรุณาเลือกรูปหลักฐาน");setBusy(true);try{const form=new FormData();form.append("type",type);form.append("image",image);if(type==="airdrop")form.append("round",round);else form.append("memberIds",JSON.stringify(crew));const r=await fetch("/api/upload",{method:"POST",body:form}),x:any=await r.json();setNotice(x.error||"ส่งเข้าคิวตรวจแล้ว");if(!x.error){setImage(null);setCrew([]);await load()}}catch{setNotice("ส่งรูปไม่สำเร็จ ลองใหม่อีกครั้ง")}finally{setBusy(false)}};
 const logout=async()=>{await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"logout"})});setData(null);setAuthNeeded(true);setLoginName("");};
 const login=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const r=await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:loginName})}),x:any=await r.json();if(x.error)setNotice(x.error);else await load()}catch{setNotice("เข้าสู่ระบบไม่สำเร็จ ลองใหม่อีกครั้ง")}finally{setBusy(false)}};
 if(!data&&authNeeded)return <main className="grid min-h-screen place-items-center bg-[#07080b] p-5 text-white"><section className="command-panel w-full max-w-md p-7 text-center"><img src="/5k-logo.png" alt="5K Fivethousand" className="mx-auto h-28 w-full object-contain"/><h1 className="mt-5 text-2xl font-black">เข้าสู่ระบบแก๊ง</h1><p className="mt-3 text-sm text-slate-400">พิมพ์ชื่อสมาชิกของคุณเพื่อเข้าใช้งาน</p><form onSubmit={login} className="mt-6 space-y-3"><input required minLength={2} maxLength={60} value={loginName} onChange={e=>setLoginName(e.target.value)} placeholder="ชื่อสมาชิก" className="w-full rounded-lg border border-white/15 bg-black/30 px-4 py-3"/><button disabled={busy} className="red-action w-full disabled:opacity-40">เข้าสู่ระบบ</button></form>{notice&&<p className="mt-4 text-sm text-red-300">{notice}</p>}</section></main>;
 if(!data)return <main className="grid min-h-screen place-items-center bg-[#07080b] text-white">กำลังเปิดศูนย์บัญชาการ…</main>;
 const members=[...data.members].sort((a,b)=>Number(data.favorites.includes(b.id))-Number(data.favorites.includes(a.id))||a.display_name.localeCompare(b.display_name));
 const nav:[string,string,any][]=[["airdrop","แอร์ดรอป",Crosshair],["party","ปาร์ตี้",Users],["score","คะแนน",Trophy],["admin","จัดการแก๊ง",ShieldCheck]];
 return <main className="min-h-screen bg-[#07080b] text-white"><div className="command-grid fixed inset-0 pointer-events-none opacity-30"/><div className="relative mx-auto flex max-w-7xl gap-6 p-4 lg:p-7"><aside className="hidden w-60 shrink-0 lg:block"><img src="/5k-logo.png" alt="5K Fivethousand" className="h-28 w-full object-contain"/><nav className="mt-7 space-y-2">{nav.map(([id,label,Icon]:any)=><button key={id} onClick={()=>setView(id)} className={`flex w-full items-center gap-3 rounded-lg px-4 py-3 text-left font-bold ${view===id?"bg-red-600":"text-slate-400 hover:bg-white/5"}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav></aside><section className="min-w-0 flex-1"><header className="mb-6 flex items-center justify-between border-b border-white/10 pb-4"><div><img src="/5k-logo.png" alt="5K" className="h-12 w-24 object-contain lg:hidden"/><p className="hidden text-sm text-slate-400 lg:block">{data.date} · ประเทศไทย</p></div><div className="flex items-center gap-3 text-right"><div><b>{data.me.name}</b><p className="text-xs text-red-400">{data.me.role==="admin"?"ADMINISTRATOR":"MEMBER"}</p></div><button onClick={logout} aria-label="ออกจากระบบ" className="rounded-lg border border-white/15 p-2 text-slate-300 hover:text-white"><LogOut className="h-4 w-4"/></button></div></header><div className="command-hero mb-5 rounded-xl border border-red-500/25 p-5"><p className="label">FIVETHOUSAND COMMAND CENTER</p><div className="mt-2 flex items-end justify-between gap-4"><div><h1 className="text-2xl font-black sm:text-3xl">แต้มของคุณ <span className="text-red-500">{data.me.score} PTS</span></h1><p className="mt-2 text-sm text-slate-400">แอร์ดรอป 2 รอบ: +3 ต่อรอบ · ปาร์ตี้ 1–5 คน: +1 ต่อคนเมื่อผ่าน</p></div><button onClick={load} className="rounded-lg border border-white/15 px-3 py-2 text-sm">รีเฟรช</button></div></div><div className="mb-5 flex gap-2 overflow-x-auto lg:hidden">{nav.map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm ${view===id?"bg-red-600":"bg-white/10"}`}>{label}</button>)}</div>{notice&&<div className="mb-5 flex items-center justify-between rounded-lg border border-red-400/30 bg-red-950/30 px-4 py-3 text-sm"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
 {view==="airdrop"&&<div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><form onSubmit={e=>send("airdrop",e)} className="command-panel p-5"><p className="label">AIRDROP CHECK-IN</p><h2 className="mt-2 text-xl font-black">ส่งหลักฐานแอร์ดรอป</h2><div className="mt-5 grid grid-cols-2 gap-3">{(["20:00","22:00"] as const).map(time=>{const entry=mine.get(time);return <button type="button" key={time} onClick={()=>setRound(time)} className={`rounded-lg border p-4 text-left ${round===time?"border-red-500 bg-red-950/30":"border-white/10"}`}><b className="text-2xl">{time}</b><p className="mt-3">{entry?<Status value={entry.status}/>:<span className="text-sm text-slate-400">ยังไม่ส่ง</span>}</p></button>})}</div><div className="mt-5"><Picker onChange={setImage}/></div><button disabled={busy||!!mine.get(round)&&mine.get(round)?.status!=="rejected"} className="red-action mt-4 w-full disabled:opacity-40"><Upload className="h-5 w-5"/>{mine.get(round)?.status==="rejected"?"ส่งหลักฐานใหม่":"ส่งรอบ "+round}</button></form><section className="command-panel p-5"><p className="label">ประวัติแอร์ดรอป</p><div className="mt-4 space-y-2">{data.airdrops.length?data.airdrops.map((x:any)=><div key={x.id} className="flex items-center justify-between rounded-lg bg-white/5 p-3"><div><b>{x.activity_date} · รอบ {x.round_time}</b><p className="text-xs text-slate-500">{new Date(x.created_at).toLocaleString("th-TH")}</p></div><Status value={x.status}/></div>):<p className="text-slate-400">ยังไม่มีประวัติ</p>}</div></section></div>}
 {view==="party"&&<div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><form onSubmit={e=>send("party",e)} className="command-panel p-5"><div className="flex justify-between"><div><p className="label">AD-HOC PARTY</p><h2 className="mt-2 text-xl font-black">รวมตี้ใหม่สำหรับกิจกรรมนี้</h2></div><b className="text-red-400">{crew.length}/5 คน</b></div><p className="mt-2 text-sm text-slate-400">เลือกได้ 1–5 คน ตี้นี้ใช้ครั้งเดียว แล้วรวมทีมใหม่ในกิจกรรมถัดไปได้ทันที</p><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{members.map((member:any)=>{const chosen=crew.includes(member.id),star=data.favorites.includes(member.id);return <div key={member.id} className={`relative rounded-lg border ${chosen?"border-red-500 bg-red-950/30":"border-white/10"}`}><button type="button" onClick={()=>setCrew(current=>chosen?current.filter(id=>id!==member.id):current.length<5?[...current,member.id]:current)} className="w-full p-3 text-left"><b className="block truncate">{member.display_name}</b><span className="text-xs text-slate-500">{member.role}</span></button><button type="button" aria-label="ติดดาวสมาชิก" onClick={()=>call({action:"favorite",memberId:member.id,enabled:!star})} className={`absolute right-2 top-2 ${star?"text-amber-300":"text-slate-600"}`}><Star className={`h-4 w-4 ${star?"fill-current":""}`}/></button></div>})}</div><div className="mt-5"><Picker onChange={setImage}/></div><button disabled={busy||crew.length<1} className="red-action mt-4 w-full disabled:opacity-40"><Camera className="h-5 w-5"/>สร้างตี้และส่งรูป</button></form><section className="command-panel p-5"><p className="label">ประวัติปาร์ตี้</p><div className="mt-4 space-y-2">{data.parties.length?data.parties.map((party:any)=><div key={party.id} className="rounded-lg bg-white/5 p-3"><div className="flex justify-between gap-2"><b>กิจกรรม #{party.id}</b><Status value={party.status}/></div><p className="mt-2 text-sm text-slate-400">{party.members}</p></div>):<p className="text-slate-400">ยังไม่มีรายการปาร์ตี้</p>}</div></section></div>}
 {view==="score"&&<section className="command-panel overflow-hidden"><div className="border-b border-white/10 p-5"><p className="label">SQUAD RANKING</p><h2 className="mt-2 text-xl font-black">ตารางคะแนนจริง</h2></div>{data.leaderboard.map((member:any,index:number)=><div className="flex items-center gap-4 border-b border-white/10 p-4 last:border-0" key={member.id}><b className="w-8 text-red-400">{index+1}</b><span className="flex-1 font-bold">{member.display_name}</span><b className="font-mono text-red-400">{member.score} PTS</b></div>)}</section>}
 {view==="admin"&&(data.me.role!=="admin"?<section className="command-panel p-6">หน้านี้สำหรับแอดมินเท่านั้น</section>:<div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="command-panel p-5"><p className="label">VERIFY QUEUE</p><h2 className="mt-2 text-xl font-black">รายการรอตรวจ</h2><div className="mt-4 space-y-3">{data.pending.length?data.pending.map((item:any)=><div key={item.type+item.id} className="rounded-lg border border-white/10 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><b>{item.type==="party"?"ปาร์ตี้":"แอร์ดรอป"} #{item.id}</b><p className="text-sm text-slate-400">{item.detail}{item.submitted_by&&<><span className="mx-1">·</span>ส่งโดย {item.submitted_by}</>}</p></div><div className="flex gap-2"><a className="rounded bg-white/10 px-3 py-2 text-sm" href={`/api/image/${item.image_key}`} target="_blank">ดูรูป</a><button disabled={busy} aria-label="อนุมัติ" onClick={()=>call({action:"approve",type:item.type,id:item.id})} className="rounded bg-emerald-600 px-3 py-2 text-sm"><Check className="h-4 w-4"/></button><button disabled={busy} onClick={()=>call({action:"reject",type:item.type,id:item.id})} className="rounded bg-red-700 px-3 py-2 text-sm">ไม่ผ่าน</button></div></div></div>):<p className="text-slate-400">ไม่มีรายการรอตรวจ</p>}</div></section><section className="command-panel p-5"><p className="label">SQUAD MANAGEMENT</p><h2 className="mt-2 text-xl font-black">เพิ่มสมาชิก</h2><form onSubmit={event=>{event.preventDefault();if(name.trim()){call({action:"member",name});setName("")}}} className="mt-4 flex gap-2"><input required minLength={2} maxLength={60} value={name} onChange={(event:ChangeEvent<HTMLInputElement>)=>setName(event.target.value)} placeholder="ชื่อสมาชิก" className="min-w-0 flex-1 rounded-lg border border-white/15 bg-black/30 px-3 py-2"/><button className="rounded-lg bg-red-600 px-3 font-bold">เพิ่ม</button></form><p className="mt-3 text-xs text-slate-400">เพิ่มด้วยชื่อได้ทันที สมาชิกใช้ชื่อนี้เพื่อเข้าใช้งาน</p><p className="mt-5 text-sm text-slate-400">สมาชิกทั้งหมด {data.managedMembers.length} คน</p><div className="mt-4 space-y-2">{data.managedMembers.map((member:any)=><div key={member.id} className="flex items-center gap-2 rounded-lg bg-white/5 p-3"><span className="flex-1"><b>{member.display_name}</b><span className="ml-2 text-xs text-slate-500">{member.active?"ใช้งาน":"ปิดใช้งาน"}</span></span><button type="button" disabled={!member.active} onClick={()=>{const next=window.prompt("แก้ชื่อสมาชิก",member.display_name);if(next)call({action:"member_update",id:member.id,name:next})}} className="rounded bg-white/10 px-2 py-1 text-xs">แก้ชื่อ</button>{member.id!==data.me.id&&member.active&&<button type="button" onClick={()=>{if(window.confirm("ปิดใช้งานสมาชิกนี้?"))call({action:"member_delete",id:member.id})}} className="rounded bg-red-700/70 px-2 py-1 text-xs">ปิดใช้งาน</button>}</div>)}</div></section></div>)}
 </section></div></main>;
}
