import { env } from "cloudflare:workers";

const thaiDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok"}).format(new Date());
const now=()=>new Date().toISOString();
const json=(data:unknown,status=200)=>Response.json(data,{status});
async function currentMember(request:Request){const c=request.headers.get("cookie")?.match(/(?:^|;\s*)fivek_session=([^;]+)/);if(!c)return null;return env.DB.prepare("SELECT m.* FROM sessions s JOIN members m ON m.id=s.member_id WHERE s.token=? AND s.expires_at>? AND m.active=1").bind(c[1],now()).first<any>();}
async function requireMember(request:Request){const member=await currentMember(request);if(!member)throw Error("กรุณาเข้าสู่ระบบก่อนใช้งาน");return member;}
async function requireAdmin(request:Request){const member=await requireMember(request);if(member.role!=="admin")throw Error("เฉพาะแอดมินเท่านั้น");return member;}
const validType=(type:unknown)=>{if(type!=="airdrop"&&type!=="party")throw Error("ประเภทไม่ถูกต้อง");return type;};

export async function GET(request:Request){try{const me=await requireMember(request),date=thaiDate();const [members,airdrops,parties,favorites,leaderboard,managed]=await Promise.all([
 env.DB.prepare("SELECT id,display_name,role FROM members WHERE active=1 ORDER BY display_name").all(),
 env.DB.prepare("SELECT id,activity_date,round_time,status,image_key,created_at FROM airdrop_submissions WHERE member_id=? ORDER BY activity_date DESC,round_time DESC LIMIT 30").bind(me.id).all(),
 env.DB.prepare("SELECT pa.id,pa.status,pa.image_key,pa.activity_date,pa.created_at,GROUP_CONCAT(allm.display_name,' · ') AS members FROM party_activities pa JOIN party_activity_members mine ON mine.party_activity_id=pa.id AND mine.member_id=? JOIN party_activity_members allpam ON allpam.party_activity_id=pa.id JOIN members allm ON allm.id=allpam.member_id GROUP BY pa.id ORDER BY pa.created_at DESC LIMIT 30").bind(me.id).all(),
 env.DB.prepare("SELECT favorite_member_id FROM member_favorites WHERE owner_member_id=?").bind(me.id).all(),
 env.DB.prepare("SELECT m.id,m.display_name,COALESCE(SUM(pl.points),0) AS score FROM members m LEFT JOIN point_ledger pl ON pl.member_id=m.id WHERE m.active=1 GROUP BY m.id ORDER BY score DESC,m.display_name LIMIT 25").all(),
 me.role==="admin"?env.DB.prepare("SELECT id,username,display_name,role,active FROM members ORDER BY active DESC,display_name").all():Promise.resolve({results:[]})
 ]);const pending=me.role==="admin"?await env.DB.prepare("SELECT * FROM (SELECT 'airdrop' AS type,a.id,a.image_key,a.round_time AS detail,a.created_at,m.display_name AS submitted_by FROM airdrop_submissions a JOIN members m ON m.id=a.member_id WHERE a.status='pending' UNION ALL SELECT 'party' AS type,pa.id,pa.image_key,'ปาร์ตี้' AS detail,pa.created_at,submitter.display_name AS submitted_by FROM party_activities pa LEFT JOIN members submitter ON submitter.id=pa.submitted_by_member_id WHERE pa.status='pending') ORDER BY created_at DESC").all():{results:[]};const score=await env.DB.prepare("SELECT COALESCE(SUM(points),0) AS total FROM point_ledger WHERE member_id=?").bind(me.id).first<any>();return json({me:{id:me.id,name:me.display_name,role:me.role,score:score?.total||0},date,members:members.results,managedMembers:managed.results,airdrops:airdrops.results,parties:parties.results,favorites:favorites.results.map((x:any)=>x.favorite_member_id),leaderboard:leaderboard.results,pending:pending.results});
}catch(error){const message=error instanceof Error?error.message:"โหลดข้อมูลไม่สำเร็จ";return json({error:message},message.includes("เข้าสู่ระบบ")?401:500)}}

export async function POST(request:Request){try{const me=await requireMember(request),body=await request.json<any>();if(body.action==="favorite"){const id=Number(body.memberId);if(!id||id===me.id)throw Error("เลือกสมาชิกไม่ถูกต้อง");const target=await env.DB.prepare("SELECT id FROM members WHERE id=? AND active=1").bind(id).first();if(!target)throw Error("ไม่พบสมาชิกที่ใช้งานอยู่");if(body.enabled)await env.DB.prepare("INSERT OR IGNORE INTO member_favorites (owner_member_id,favorite_member_id,created_at) VALUES (?,?,?)").bind(me.id,id,now()).run();else await env.DB.prepare("DELETE FROM member_favorites WHERE owner_member_id=? AND favorite_member_id=?").bind(me.id,id).run();return json({ok:true});}
if(body.action==="approve"){const admin=await requireAdmin(request),type=validType(body.type),id=Number(body.id),table=type==="party"?"party_activities":"airdrop_submissions",points=type==="party"?1:3,target=await env.DB.prepare(`SELECT id,status FROM ${table} WHERE id=?`).bind(id).first<any>();if(!target||target.status!=="pending")throw Error("รายการนี้ตรวจไปแล้วหรือไม่พบข้อมูล");const recipients=type==="party"?await env.DB.prepare("SELECT member_id FROM party_activity_members WHERE party_activity_id=?").bind(id).all<any>():{results:[await env.DB.prepare("SELECT member_id FROM airdrop_submissions WHERE id=?").bind(id).first<any>()]};await env.DB.batch([env.DB.prepare(`UPDATE ${table} SET status='approved',approved_by=? WHERE id=? AND status='pending'`).bind(admin.id,id),...recipients.results.filter(Boolean).map((r:any)=>env.DB.prepare("INSERT OR IGNORE INTO point_ledger (member_id,source,source_id,points,note,created_at) VALUES (?,?,?,?,?,?)").bind(r.member_id,type,id,points,type==="party"?"ปาร์ตี้ตรวจผ่าน":"แอร์ดรอปตรวจผ่าน",now()))]);return json({ok:true});}
if(body.action==="reject"){const admin=await requireAdmin(request),type=validType(body.type),table=type==="party"?"party_activities":"airdrop_submissions",r=await env.DB.prepare(`UPDATE ${table} SET status='rejected',approved_by=? WHERE id=? AND status='pending'`).bind(admin.id,Number(body.id)).run();if(!r.meta.changes)throw Error("รายการนี้ตรวจไปแล้วหรือไม่พบข้อมูล");return json({ok:true});}
if(body.action==="member"){await requireAdmin(request);const name=String(body.name||"").trim();if(name.length<2||name.length>60)throw Error("กรอกชื่อสมาชิก 2–60 ตัวอักษร");const exists=await env.DB.prepare("SELECT id FROM members WHERE lower(display_name)=lower(?)").bind(name).first();if(exists)throw Error("มีชื่อสมาชิกนี้แล้ว");await env.DB.prepare("INSERT INTO members (username,display_name,role,active,created_at) VALUES (?,?,'member',1,?)").bind(`${name}-${Date.now()}-${crypto.randomUUID().slice(0,6)}`,name,now()).run();return json({ok:true});}
if(body.action==="member_update"){await requireAdmin(request);const id=Number(body.id),name=String(body.name||"").trim();if(!id||name.length<2||name.length>60)throw Error("กรอกชื่อสมาชิก 2–60 ตัวอักษร");const exists=await env.DB.prepare("SELECT id FROM members WHERE lower(display_name)=lower(?) AND id<>?").bind(name,id).first();if(exists)throw Error("มีชื่อสมาชิกนี้แล้ว");const r=await env.DB.prepare("UPDATE members SET display_name=? WHERE id=? AND active=1").bind(name,id).run();if(!r.meta.changes)throw Error("ไม่พบสมาชิกที่ใช้งานอยู่");return json({ok:true});}
if(body.action==="member_delete"){const admin=await requireAdmin(request),id=Number(body.id);if(!id||id===admin.id)throw Error("ไม่สามารถปิดใช้งานบัญชีแอดมินตัวเอง");await env.DB.batch([env.DB.prepare("UPDATE members SET active=0 WHERE id=?").bind(id),env.DB.prepare("DELETE FROM sessions WHERE member_id=?").bind(id)]);return json({ok:true});}throw Error("คำสั่งไม่ถูกต้อง");
}catch(error){return json({error:error instanceof Error?error.message:"บันทึกไม่สำเร็จ"},400)}}
